Update adobject.py
pyad.from_cn(u"SomeGroupWithAnEMDash – OrOtherUnicodeCharracter")
Traceback (most recent call last):
  File "<pyshell#54>", line 1, in <module>
    pyad.from_cn(u"ABU Gorgon Ops Data – Gorgon Operations")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 33: ordinal not in range(128)

Caused by attempting to return __str__(self) to the console as an ASCII text string containing Unicode characters